:encoding: utf-8
:imagesdir: tutorials/img
:cpp: C++

= VRPTW solutions 

This repo contains:

- A collection of VRPTW benchmark solutions for open source tools.
- Code for solution generation.
- Code to verify / compare solutions.
- A comparison with reference solutions.

=== Motivation

As part of the documentation of the optimization library https://github.com/dietmarwo/fast-cma-es/[fcmaes] we have shown
that continuous optimization is a valid choice for optimizing route planning as long as we are faced with non-standard 
requirements, see: 

- https://github.com/dietmarwo/fast-cma-es/blob/master/tutorials/UAV.adoc[Multi-UAV] Multi-UAV Task Assignment.  
- https://github.com/dietmarwo/fast-cma-es/blob/master/tutorials/TSP.adoc[Noisy TSP] Solve the noisy Traveling Salesman Problem.  
- https://github.com/dietmarwo/fast-cma-es/blob/master/tutorials/Scheduling.adoc[Scheduling] Solving a complex scheduling problem, part of the GTOC11 competition.

How far behind is continuous optimization for a typical standard problem well covered by
specialized libraries? To evaluate this question we choose the 100 customer instances of Solomon's VRPTW benchmark problems from 1987 because
it is used until recently as a reference for comparison of open source tools (
https://www.confer.cz/clc/2019/2922-comparison-of-capabilities-of-recent-open-source-tools-for-solving-capacitated-vehicle-routing-problems[Duda2019]).
and there are reference solutions available (https://www.sintef.no/projectweb/top/vrptw/100-customers/ , http://web.cba.neu.edu/~msolomon/problems.htm ).

The goal is not to replace specific methods like or-tools by generic continuous optimization. Instead we investigate which specific continuous 
optimizer works best for VRPTW. This optimizer then could be applied to non-standard variations of the VRPTW problem 
not covered by the specialized tools. Keep in mind: The only thing we need is a fitness function, there are no "incremental changes" or 
"specific gene representations" as usually required by other methods. 

During our tests we indeed found a combination of algorithms never before used in combination: 
A sequence of CRM-FNES and BiteOpt. We found that CRM-FNES converges very fast, but then always gets caught in a local minimum.
BiteOpt on the other hand converges slower, but is better at escaping local minima. Applying both in a sequence looks like a 
natural choice. 

=== The Solomons Benchmark

There exist two different objectives for the Solomon's VRPTW benchmark:

- Minimizing the overall distance / time serving all customers http://web.cba.neu.edu/~msolomon/problems.htm[solomon] 
- A hierarchical objective minimizing the number of vehicles with the distance as secondary objective (https://www.sintef.no/projectweb/top/vrptw/100-customers/[sintef])

Unfortunately for the distance-objective we couldn't find reference solutions. And for both objectives there are no solution sets available
for existing open source tools. In this github repository we want to collect these, starting with or-tools and continuous optimization. 
Creation of the solution sets should be reproducible, so we added the code which computes them. Feel free to create a PR if you
find an improvement or want to add another open source tool. 

We applied the hierarchical objective only to or-tools to compare them with the https://www.sintef.no/projectweb/top/vrptw/100-customers/[sintef] reference solutions.
The single distance objective was applied both to or-tools and continuous optimization, with the or-tools result as reference. 
There are only minimal differences to the http://web.cba.neu.edu/~msolomon/problems.htm[solomon] reference results. 

=== Summary of the Results

See https://github.com/dietmarwo/VRPTW/blob/master/Results.adoc[results] for detailed results. 

Summary:

- or-tools almost reproduces the reference solutions if given enough time (3 hours) 
- or-tools solves the clustered problems quite fast (< 1 min single threaded)
- or-tools has sometimes problems with the hierarchical objective, if the number of vehicles is very small. 
- for the single (distance) objective the new or-tools results are better then all reported results at
https://www.confer.cz/clc/2019/2922-comparison-of-capabilities-of-recent-open-source-tools-for-solving-capacitated-vehicle-routing-problems[Duda2019] - 
with the exception of RC1, were Duda2019 reports an average of 1348.51 for jsprit and the or-tools result is 1360.90 .

So we can use the or-tools single objective results as open-source-tool reference for the Solomon's benchmark.  

- Applying continuous optimization results in an error rate between 3% and 8% when about 8 minutes walltime are invested
for each problem on a AMD 5950x CPU utilizing all 16 cores / 32 threads. 

- The error rate is lower for the clustered problems. 

=== Results



.Average distance hierarchical objective
[width="70%", options="header"]
|===
|optimizer|C1|C2|R1|R2|RC1|RC2
|sintef|828.4|589.9|1231.1|968.2|1406.1|1089.8
|or-tools|828.5|598.7|1209.0|928.6|1385.6|1114.8
|%difference|0.02|1.5|-1.79|-4.09|-1.46|2.29
|===

.Average number of vehicles hierarchical objective
[width="70%", options="header"]
|===
|optimizer|C1|C2|R1|R2|RC1|RC2
|sintef|10.0|3.0|12.18|2.88|11.57|3.33
|or-tools|10.0|3.12|12.42|3.09|12.12|3.38
|%difference|0.0|4.17|1.93|7.51|4.78|1.25
|===

.Average distance single objective
[width="70%", options="header"]
|===
|optimizer|C1|C2|R1|R2|RC1|RC2
|or-tools|828.4|589.9|1182.6|878.0|1360.9|1005.3
|continuous|829.3|591.8|1221.6|909.7|1384.2|1035.2
|%difference|0.11|0.34|3.3|3.61|1.71|2.97
|===

.Average number of vehicles single objective
[width="70%", options="header"]
|===
|optimizer|C1|C2|R1|R2|RC1|RC2
|or-tools|10.0|3.0|13.33|5.45|13.12|6.25
|continuous|10.0|3.0|14.0|5.36|13.88|6.75
|%difference|0.0|0.0|5.0|-1.67|5.71|8.0
|===



.VRT results
[width="50%", options="header"]
|===
|problem |vehicles | distance | veh % | dist %
|c101|11|828.9|0.0|0.0
|c102|11|828.9|0.0|0.0
|c103|11|828.1|0.0|-0.0
|c104|11|825.6|0.0|0.11
|c105|11|828.9|0.0|0.0
|c106|11|828.9|0.0|0.0
|c107|11|828.9|0.0|0.0
|c108|11|828.9|0.0|0.0
|c109|11|829.4|0.0|0.05
|c201|4|591.6|0.0|-0.0
|c202|4|591.6|0.0|-0.0
|c203|4|591.2|0.0|-0.0
|c204|4|593.9|0.0|0.56
|c205|4|588.9|0.0|-0.0
|c206|4|588.5|0.0|-0.0
|c207|4|588.3|0.0|0.0
|c208|5|655.9|25.0|11.48
|r101|20|1651.2|0.0|0.03
|r102|18|1487.0|0.0|0.06
|r103|14|1303.5|0.0|0.83
|r104|11|1002.1|10.0|-0.52
|r105|15|1385.3|0.0|0.6
|r106|13|1267.8|0.0|1.26
|r107|11|1141.3|0.0|3.32
|r108|11|956.9|10.0|-0.42
|r109|13|1162.6|8.33|-2.69
|r110|12|1106.6|9.09|-1.09
|r111|12|1071.4|9.09|-2.31
|r112|11|972.3|???|???
|r201|5|1257.8|0.0|0.43
|r202|5|1097.7|25.0|-7.89
|r203|4|949.4|???|???
|r204|4|753.2|33.33|-8.76
|r205|4|1021.6|0.0|2.73
|r206|4|916.9|0.0|1.19
|r207|4|820.5|???|???
|r208|3|730.5|0.0|0.51
|r209|4|919.9|0.0|1.18
|r210|4|956.3|0.0|1.8
|r211|4|790.3|???|???
|rc101|16|1632.0|6.67|-3.83
|rc102|14|1528.8|7.69|-1.67
|rc103|12|1326.1|0.0|5.11
|rc104|11|1151.2|0.0|1.38
|rc105|15|1593.0|7.14|-2.24
|rc106|13|1441.5|8.33|1.18
|rc107|12|1262.4|???|???
|rc108|12|1149.7|9.09|0.87
|rc201|5|1437.3|0.0|2.16
|rc202|5|1161.3|???|???
|rc203|4|1097.6|???|???
|rc204|4|801.6|0.0|0.4
|rc205|5|1311.9|0.0|1.1
|rc206|4|1184.2|0.0|3.31
|rc207|4|1085.2|0.0|2.27
|rc208|4|839.1|0.0|1.33
|===

.VRT results 2
[width="50%", options="header"]
|===
|problem |vehicles | distance | veh % | dist %
|c101|11|828.9|0.0|0.0
|c102|11|828.9|0.0|0.0
|c103|11|828.1|0.0|-0.0
|c104|11|824.8|0.0|0.0
|c105|11|828.9|0.0|0.0
|c106|11|828.9|0.0|0.0
|c107|11|828.9|0.0|0.0
|c108|11|828.9|0.0|0.0
|c109|11|828.9|0.0|0.0
|c201|4|591.6|0.0|0.0
|c202|4|591.6|0.0|-0.0
|c203|4|591.2|0.0|-0.0
|c204|4|590.6|0.0|-0.0
|c205|4|588.9|0.0|-0.0
|c206|4|588.5|0.0|-0.0
|c207|4|588.3|0.0|-0.0
|c208|4|588.3|0.0|0.0
|r101|21|1643.4|5.0|-0.45
|r102|19|1472.8|5.56|-0.9
|r103|15|1213.6|7.14|-6.12
|r104|12|983.8|20.0|-2.34
|r105|16|1360.8|6.67|-1.19
|r106|14|1240.6|7.69|-0.91
|r107|12|1077.5|9.09|-2.46
|r108|12|953.1|20.0|-0.81
|r109|14|1151.9|16.67|-3.59
|r110|13|1083.5|18.18|-3.16
|r111|13|1054.6|18.18|-3.84
|r112|11|955.7|???|???
|r201|9|1148.0|80.0|-8.34
|r202|9|1036.5|125.0|-13.03
|r203|7|875.6|???|???
|r204|6|735.8|100.0|-10.87
|r205|6|956.0|50.0|-3.86
|r206|6|881.6|50.0|-2.71
|r207|5|798.1|???|???
|r208|5|706.2|66.67|-2.84
|r209|6|859.9|50.0|-5.42
|r210|7|904.8|75.0|-3.68
|r211|5|755.9|???|???
|rc101|18|1647.3|20.0|-2.93
|rc102|15|1478.6|15.38|-4.9
|rc103|13|1319.4|8.33|4.57
|rc104|11|1150.9|0.0|1.35
|rc105|17|1532.1|21.43|-5.97
|rc106|14|1385.9|16.67|-2.73
|rc107|13|1236.3|???|???
|rc108|12|1137.0|9.09|-0.25
|rc201|10|1265.8|100.0|-10.03
|rc202|9|1096.5|???|???
|rc203|6|935.2|???|???
|rc204|5|786.4|25.0|-1.51
|rc205|8|1157.7|60.0|-10.79
|rc206|8|1054.6|100.0|-8.0
|rc207|7|966.4|75.0|-8.93
|rc208|5|780.1|25.0|-5.81
|===

